center_sys/account/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^success/$', views.success, name='success'),
    url(r'^pay_order/(?P<order_id>\d+)/$', views.pay_order, name='pay_order'),
    url(r'^cancel_order/(?P<order_id>\d+)/$', views.cancel_order, name='cancel_order'),
)

center_sys/center_sys/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc', name='xmlrpc'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

center_sys/center_sys/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

center_sys/center_sys/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
    {{ form.media }}
  </head>
  <body>
    <div class="container">
    <h1></h1>
    
    <a href="{% url 'index' %}">Главная</a>
    <a href="{% url 'catalog:index' %}">Каталог</a>
    <a href="{% url 'account:index' %}">Профиль</a>
    
    {% if user.is_authenticated %}
        <p>Добро пожаловать, <b>{{ user.username }}</b>. <a href="{% url 'account:logout' %}">выйти</a></p>
    {% else %}
        <p>Вы не авторизированы. <a href="{% url 'account:login' %}">войдите</a>.</p>
    {% endif %}

    {% block content %}
    {% endblock %}

    </div>

  </body>
</html>

center_sys/center_sys/templates/index.html
{% extends 'base.html' %}

{% block content %}
<ul>
<li><a href="{% url 'catalog:index' %}">Каталог</a></li>
<li><a href="{% url 'account:index' %}">Личная страница</a></li>
</ul>
{% endblock %}

center_sys/center_sys/templates/message.html
{{ result }}

center_sys/center_sys/templates/pager.html
<div class="row">
    <div class="col-md-4 col-md-offset-5">
    {% if items.has_previous %}
        <a href="?{{queries.urlencode}}&amp;page={{ items.previous_page_number }}"><<</a>
    {% endif %}

    <span class="current">
        {{ items.number }} / {{ items.paginator.num_pages }}
    </span>

    {% if items.has_next %}
        <a href="?{{queries.urlencode}}&amp;page={{ items.next_page_number }}">>></a>
    {% endif %}
    </div>
</div>